package insa.singleton;

// This code has been generated by IntelliJ.
// This is another way to have a singleton in Java.
// The final keyword is in fact optional since a private constructor prevents any inheritance.
public class AnotherSingleton {
	private static AnotherSingleton ourInstance = new AnotherSingleton();

	public static AnotherSingleton getInstance() {
		return ourInstance;
	}

	private AnotherSingleton() {
	}
}
